In [103]:
import torch

In [104]:
#Valores arbitrarios
# torch.empty(10)

In [105]:
torch.rand(3,2)

tensor([[0.3179, 0.2872],
        [0.8067, 0.9225],
        [0.8800, 0.0684]])

In [106]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [107]:
torch.ones(3, 4, 2)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [108]:
torch.ones(2,2, dtype = torch.double)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [109]:
a = torch.tensor([1,2,3])
b = torch.tensor([100,200,300])
a*b

tensor([100, 400, 900])

In [110]:
a+b

tensor([101, 202, 303])

In [111]:
a.add(b)

tensor([101, 202, 303])

In [112]:
import numpy as np
d = torch.ones(5)
d.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [113]:
# Form numpy

In [114]:
torch.ones(5, requires_grad = True)

tensor([1., 1., 1., 1., 1.], requires_grad=True)

In [115]:
# Gradients

In [116]:
# Gradientes
x = torch.randn(3)

Ejemplo 1

In [117]:
x = torch.tensor([3.0,5.0,7.0], requires_grad = True)
print(x)

tensor([3., 5., 7.], requires_grad=True)
tensor([3., 5., 7.], requires_grad=True)


In [118]:
y = x + 2
print(y)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)
tensor([5., 7., 9.], grad_fn=<AddBackward0>)


In [119]:
y=2*y*y
print(y)

tensor([ 50.,  98., 162.], grad_fn=<MulBackward0>)
tensor([ 50.,  98., 162.], grad_fn=<MulBackward0>)


Entra un escalar en la segunda función

In [120]:
z = y.mean()
print(z)

tensor(103.3333, grad_fn=<MeanBackward0>)
tensor(103.3333, grad_fn=<MeanBackward0>)


In [121]:
z.backward()
print(x.grad)

tensor([ 6.6667,  9.3333, 12.0000])
tensor([ 6.6667,  9.3333, 12.0000])


In [122]:
Posibles problemas

SyntaxError: invalid syntax (2361028999.py, line 1)

In [ ]:
x = torch.tensor([3.0,5.0,7.0], requires_grad = True)
y = x + 2
y=2*y*y

In [123]:
#El método backward solo funciona para escalar
#y.backward()

Segundo ejemplo

In [125]:
x = torch.tensor([3.0,5.0,7.0], requires_grad = True)
y = x + 2
y=2*y*y
v = torch.tensor([10, 11, 12])
y.backward(v)
print(x.grad)

tensor([200., 308., 432.])
tensor([200., 308., 432.])


Caso 3: actualizar el gradiente 

In [128]:
x = torch.tensor([3.0,5.0,7.0], requires_grad = True)
x.requires_grad_(False)
print(x)

tensor([3., 5., 7.])
tensor([3., 5., 7.])


In [129]:
# Otra opción con detach
y = x.detach()
print(y)

tensor([3., 5., 7.])
tensor([3., 5., 7.])


In [130]:
# Con with torch.nograd()
x = torch.tensor([3.0,5.0,7.0], requires_grad = True)
with torch.no_grad():
    y = x + 2
    print(y)

tensor([5., 7., 9.])
tensor([5., 7., 9.])


Back propagation

In [136]:
x = torch.tensor(3.0)
y = torch.tensor(14.0)

w = torch.tensor(4.0, requires_grad = True)




In [138]:
y_hat = w*x
loss = (y_hat-y)**2
print(loss)

tensor(4., grad_fn=<PowBackward0>)
tensor(4., grad_fn=<PowBackward0>)


In [139]:
loss.backward()
print(w.grad)

tensor(-12.)
tensor(-12.)


Algoritmo gradiente descendente

In [175]:
import numpy as np
X = np.array([1,2,3,4,5], dtype = np.float32)
Y = np.array([2,4,6,8,10], dtype = np.float32)

$$MSE(w_i)=\frac{\sum_{i=1}^n (y_i-w_ix_i)^2}{n}$$



Ahora la dericada de MSE con respecto a los pesos es: $$\frac{\partial MSE(\mathbf{w})}{\partial \mathbf{w}} = -\frac{2}{n} \sum_{i=1}^n (y_i - \mathbf{w}^\top \mathbf{x}_i) \mathbf{x}_i$$. Lo cual se puede expresar como -2*((y-w*x)*x).mean() o equivalentemente np.dot(-2*x, y - y_hat).mean

In [176]:
def forward(x):
    return w*x

def loss(y, y_hat):
    return ((y-y_hat)**2).mean() 

def gradient(x, y, y_hat):
    return np.dot(-2*x, y-y_hat).mean()       

In [177]:
lr = 0.01 # Learning Rate
n_iter = 10

#Inicializo 
w = 0.0
for epoch in range(n_iter):
    y_pred = forward(X) # implicitamente está el w
    l = loss(Y, y_pred)
    
    # Gradiente
    dL_dw = gradient(X, Y, y_pred)
    # update weights
    w = w-lr*dL_dw
    print(f'epoch:{epoch+1}; w = {w}')

epoch:1; w = 2.2
epoch:2; w = 1.9799999618530275
epoch:3; w = 2.0019999885559083
epoch:4; w = 1.99979989528656
epoch:5; w = 2.0000200200080873
epoch:6; w = 1.9999979901313782
epoch:7; w = 2.000000262260437
epoch:8; w = 2.000000009536743
epoch:9; w = 2.000000009536743
epoch:10; w = 2.000000009536743
epoch:1; w = 2.2
epoch:2; w = 1.9799999618530275
epoch:3; w = 2.0019999885559083
epoch:4; w = 1.99979989528656
epoch:5; w = 2.0000200200080873
epoch:6; w = 1.9999979901313782
epoch:7; w = 2.000000262260437
epoch:8; w = 2.000000009536743
epoch:9; w = 2.000000009536743
epoch:10; w = 2.000000009536743


Hacerlo con tensor flow y usar las funcionalidades del gradiente

In [195]:
X = torch.tensor([1,2,3,4,5], dtype = torch.float32)
Y = torch.tensor([2,4,6,8,10], dtype = torch.float32)

def forward(x):
    return w*x

def loss(y, y_hat):
    return ((y-y_hat)**2).mean() 

def gradient(x, y, y_hat):
    return np.dot(-2*x, y-y_hat).mean()       

In [199]:
lr = 0.01 # Learning Rate
n_iter = 100

#Inicializo 
w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

for epoch in range(n_iter):
    y_pred = forward(X) # implicitamente está el w
    l=loss(Y, y_pred)
    
    # Gradiente
    l.backward()
    
    # update weights
    with torch.no_grad():
        w -= lr * w.grad

    
    w.grad.zero_()
    if epoch % 10 == 0:
        print(f'epoch:{epoch+1}; w = {w}')

epoch:1; w = 0.4399999976158142
epoch:11; w = 1.8699618577957153
epoch:21; w = 1.989160418510437
epoch:31; w = 1.9990965127944946
epoch:41; w = 1.999924659729004
epoch:51; w = 1.9999936819076538
epoch:61; w = 1.9999994039535522
epoch:71; w = 1.999999761581421
epoch:81; w = 1.999999761581421
epoch:91; w = 1.999999761581421
epoch:1; w = 0.4399999976158142
epoch:11; w = 1.8699618577957153
epoch:21; w = 1.989160418510437
epoch:31; w = 1.9990965127944946
epoch:41; w = 1.999924659729004
epoch:51; w = 1.9999936819076538
epoch:61; w = 1.9999994039535522
epoch:71; w = 1.999999761581421
epoch:81; w = 1.999999761581421
epoch:91; w = 1.999999761581421


2.0

In [85]:
x = torch.tensor([3.0,5.0,7.0], requires_grad = True)
print(x)

tensor([ 6.6667,  9.3333, 12.0000])
tensor([ 6.6667,  9.3333, 12.0000])


In [56]:
print(z)

tensor(8.3887, grad_fn=<MeanBackward0>)
tensor(8.3887, grad_fn=<MeanBackward0>)


Mean backward

In [ ]:
z.backward() #dz/dz


In [44]:
torch.tensor([1,5,6.9])

tensor([1.0000, 5.0000, 6.9000])

In [20]:
tensor_a = torch.arange(1, 106).reshape(3, 7, 5).float()

# Generate a tensor of size 7 x 5 with a sequence from 100 to 134
tensor_b = torch.arange(100, 135).reshape(7, 5).float()

In [21]:
print(tensor_a)

tensor([[[  1.,   2.,   3.,   4.,   5.],
         [  6.,   7.,   8.,   9.,  10.],
         [ 11.,  12.,  13.,  14.,  15.],
         [ 16.,  17.,  18.,  19.,  20.],
         [ 21.,  22.,  23.,  24.,  25.],
         [ 26.,  27.,  28.,  29.,  30.],
         [ 31.,  32.,  33.,  34.,  35.]],

        [[ 36.,  37.,  38.,  39.,  40.],
         [ 41.,  42.,  43.,  44.,  45.],
         [ 46.,  47.,  48.,  49.,  50.],
         [ 51.,  52.,  53.,  54.,  55.],
         [ 56.,  57.,  58.,  59.,  60.],
         [ 61.,  62.,  63.,  64.,  65.],
         [ 66.,  67.,  68.,  69.,  70.]],

        [[ 71.,  72.,  73.,  74.,  75.],
         [ 76.,  77.,  78.,  79.,  80.],
         [ 81.,  82.,  83.,  84.,  85.],
         [ 86.,  87.,  88.,  89.,  90.],
         [ 91.,  92.,  93.,  94.,  95.],
         [ 96.,  97.,  98.,  99., 100.],
         [101., 102., 103., 104., 105.]]])
tensor([[[  1.,   2.,   3.,   4.,   5.],
         [  6.,   7.,   8.,   9.,  10.],
         [ 11.,  12.,  13.,  14.,  15.],
         [

In [22]:
print(tensor_b)

tensor([[100., 101., 102., 103., 104.],
        [105., 106., 107., 108., 109.],
        [110., 111., 112., 113., 114.],
        [115., 116., 117., 118., 119.],
        [120., 121., 122., 123., 124.],
        [125., 126., 127., 128., 129.],
        [130., 131., 132., 133., 134.]])
tensor([[100., 101., 102., 103., 104.],
        [105., 106., 107., 108., 109.],
        [110., 111., 112., 113., 114.],
        [115., 116., 117., 118., 119.],
        [120., 121., 122., 123., 124.],
        [125., 126., 127., 128., 129.],
        [130., 131., 132., 133., 134.]])


In [24]:

print(tensor_a + tensor_b)

tensor([[[101., 103., 105., 107., 109.],
         [111., 113., 115., 117., 119.],
         [121., 123., 125., 127., 129.],
         [131., 133., 135., 137., 139.],
         [141., 143., 145., 147., 149.],
         [151., 153., 155., 157., 159.],
         [161., 163., 165., 167., 169.]],

        [[136., 138., 140., 142., 144.],
         [146., 148., 150., 152., 154.],
         [156., 158., 160., 162., 164.],
         [166., 168., 170., 172., 174.],
         [176., 178., 180., 182., 184.],
         [186., 188., 190., 192., 194.],
         [196., 198., 200., 202., 204.]],

        [[171., 173., 175., 177., 179.],
         [181., 183., 185., 187., 189.],
         [191., 193., 195., 197., 199.],
         [201., 203., 205., 207., 209.],
         [211., 213., 215., 217., 219.],
         [221., 223., 225., 227., 229.],
         [231., 233., 235., 237., 239.]]])
tensor([[[101., 103., 105., 107., 109.],
         [111., 113., 115., 117., 119.],
         [121., 123., 125., 127., 129.],
         [

Otro ejemplo de broadcasting

In [29]:
import torch

# Generate a tensor of size 3 x 7 x 1 with a sequence from 1 to 21
tensor_c = torch.arange(1, 22).reshape(3, 7, 1).float()

# Generate a tensor of size 1 x 5 with a sequence from 100 to 104
tensor_d = torch.arange(100, 105).reshape(1, 5).float()


In [30]:
print(tensor_c)

tensor([[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.]],

        [[ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.],
         [13.],
         [14.]],

        [[15.],
         [16.],
         [17.],
         [18.],
         [19.],
         [20.],
         [21.]]])
tensor([[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.]],

        [[ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.],
         [13.],
         [14.]],

        [[15.],
         [16.],
         [17.],
         [18.],
         [19.],
         [20.],
         [21.]]])


In [31]:
print(tensor_d)

tensor([[100., 101., 102., 103., 104.]])
tensor([[100., 101., 102., 103., 104.]])


In [32]:
# Broadcast tensor_b to match the shape of tensor_a and perform an operation, e.g., addition
print(tensor_c + tensor_d)

tensor([[[101., 102., 103., 104., 105.],
         [102., 103., 104., 105., 106.],
         [103., 104., 105., 106., 107.],
         [104., 105., 106., 107., 108.],
         [105., 106., 107., 108., 109.],
         [106., 107., 108., 109., 110.],
         [107., 108., 109., 110., 111.]],

        [[108., 109., 110., 111., 112.],
         [109., 110., 111., 112., 113.],
         [110., 111., 112., 113., 114.],
         [111., 112., 113., 114., 115.],
         [112., 113., 114., 115., 116.],
         [113., 114., 115., 116., 117.],
         [114., 115., 116., 117., 118.]],

        [[115., 116., 117., 118., 119.],
         [116., 117., 118., 119., 120.],
         [117., 118., 119., 120., 121.],
         [118., 119., 120., 121., 122.],
         [119., 120., 121., 122., 123.],
         [120., 121., 122., 123., 124.],
         [121., 122., 123., 124., 125.]]])
tensor([[[101., 102., 103., 104., 105.],
         [102., 103., 104., 105., 106.],
         [103., 104., 105., 106., 107.],
         [

In [36]:
 torch.zeros(4, 3, 2, 1).add(torch.ones(4, 3, 2))

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2